= jQAssistant SonarQube Plugin

This is the SonarQube plugin for jQAssistant integration.

== Requirements
* Java 7 or higher
* SonarQube 5.1.2
* Java project with jQAssistant setup

== Installation
* Copy the plugin (i.e. JAR file) to the `plugin/extensions` folder of the SonarQube installation
* (Re-)Start the SonarQube server

== Configuration
The plugin provides two rules that need to be activated for the quality profile of your project(s).

Invalid Concept::
  Concepts that are defined but could not be applied successfully (default severity: Minor).
Constraint Violation::
  Constraints that reported violations (default severity: Major).

Therefore the following steps need to be performed in the SonarQube UI (as administrator):

* Navigate to `Quality Profiles`
* Select your desired quality profile
* Activate the jQAssistant rules
** Open the view to manage the rules of the quality profile
** Search for inactive rules in the repository `jQAssistant` (by using the filters on the left side)
** Activate the desired rules
* Add your project to the quality profile (if not already done)
** Navigate back to the overview screen of the selected quality profile
** Select `Projects`
** Add your project

== Execution
In case of a Maven project with a jQAssistant setup the following steps need to be executed

`mvn install`::
  Build the project and execute scan and analysis by jQAssistant
`mvn sonar:sonar`::
  Run the SonarQube analysis.
  The sensor of the jQAssistant SonarQube plugin will evaluate the file `target/jqassistant/jqassistant-report.xml` and
  create issues for failed rules.

