:toc: left
= Release Notes

== 1.9.0
* To allow filtering issues by rule type the plugin now creates ad-hoc rules/external issues instead of generic concept/constraint issues where possible.
  This is currently limited to issues that can be resolved to files (e.g. Java classes).
* Added detection of jQAssistant XML reports from parent modules

== 1.8.2
* Fixed https://github.com/jqassistant-contrib/sonar-jqassistant-plugin/issues/8[JAXB related regression] when running an analysis using Java version 11 or newer

== 1.8.1
* Upgraded to jQAssistant 1.8.0
* Fixed an error when creating an issue referencing a line number

== 1.7.3
* Clarified behavior of configuration property `sonar.jqassistant.reportPath`:
  Added support for absolute paths and resolving relative paths by using the current module directory
  (https://github.com/jqassistant-contrib/sonar-jqassistant-plugin/issues/10[issue])
* The primary column of a result is no longer included in the message of an issue
  if it could be matched to a source location in SonarQube (https://github.com/jqassistant-contrib/sonar-jqassistant-plugin/issues/11[issue])

== 1.7.2

* Initial entry into the SonarQube Marketplace (pending)
* Fixed https://github.com/jqassistant-contrib/sonar-jqassistant-plugin/issues/8[JAXB related error] when running an analysis using Java version 11 or newer

== 1.7.1

* Reduced size of plugin JAR file

== 1.7.0

* Migrated to SonarQube 7.9 API
* Added support for multi-module projects
* Changed name of published JAR artifact to `sonar-jqassistant-plugin-<version>.jar`

